### ISSUE TITLE
init project

### ISSUE THREAD

**Issue by nambn-code** [btcs-nambn/shop-api#1]
ghi thêm thông tin bên dưới về phiên bản, thư viện ngoài thêm vào

**Comment by btcs-manhdd** [comment]
### Phiên bản

- php: ^8.0.2
- laravel/framework: ^9.19

### Thư viện

-  guzzlehttp/guzzle: ^7.2
-  laravel/sanctum: ^3.0
-  laravel/tinker: ^2.7
-  fakerphp/faker: ^1.9.1
-  laravel/pint: ^1.0,
-  laravel/sail: ^1.0.1,
-  mockery/mockery: ^1.4.4,
-  nunomaduro/collision: ^6.1,
-  phpunit/phpunit: ^9.5.10,
-  spatie/laravel-ignition: ^1.0

**Comment by nambn-code** [comment]
không laravel 10 à

**Comment by btcs-manhdd** [comment]
em dùng câu lệnh này theo docs của version 10 mà nó ra 9 thôi
![image](https://user-images.githubusercontent.com/107126036/229004829-1804d064-167a-4962-a789-0731d651efce.png)
