### ISSUE TITLE
Phát triển api POST /api/products.json

### ISSUE THREAD

**Issue by nambn-code** [btcs-nambn/shop-api#2]
- Tạo DB cho Product và các bảng liên quan
- tạo api tạo mới product, chưa cần có variant

**Comment by btcs-manhdd** [comment]
@btcs-nambn  A check giúp em PR issue-2 với
#3

**Comment by btcs-manhdd** [comment]
Database design: https://drive.google.com/file/d/10GE4tFnjv8nx4QZs9v2nKJFYM9-cAHXm/view?usp=sharing
